# Generated by Django 4.2 on 2023-09-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Update')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.basemodel')),
                ('purches_quentity', models.PositiveIntegerField(verbose_name='Purches')),
                ('sales_quentity', models.PositiveIntegerField(verbose_name='Sales')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='products.product', verbose_name='Product')),
            ],
            bases=('inventory.basemodel',),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.basemodel')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('offer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Offer')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product', verbose_name='Product')),
            ],
            bases=('inventory.basemodel',),
        ),
        migrations.CreateModel(
            name='Purches',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.basemodel')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('offer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Offer')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purches', to='products.product', verbose_name='Product')),
            ],
            bases=('inventory.basemodel',),
        ),
    ]
