# Generated by Django 4.2 on 2023-09-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
    ]
