# Generated by Django 4.2 on 2023-09-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purches',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
    ]
