# Generated by Django 4.2 on 2023-09-18 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('inventory', '0002_alter_purches_total_alter_sale_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.basemodel')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('offer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product', verbose_name='Product')),
            ],
            bases=('inventory.basemodel',),
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.basemodel')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('offer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Offer')),
                ('sale_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_product', to='inventory.saleproduct', verbose_name='Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoice', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            bases=('inventory.basemodel',),
        ),
        migrations.RemoveField(
            model_name='purches',
            name='total',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
