# Generated by Django 4.2 on 2023-09-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_saleproduct_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='total',
            field=models.PositiveIntegerField(verbose_name='Total'),
        ),
    ]
